### ISSUE TITLE
Add debug server internals resources to tilt with a special --debug-internals flag

### ISSUE THREAD

**Issue by gamerson** [liferay/liferay-localdev#15]
If the ext environment has any trouble, it would be good if we could show customers how to invoke localdev with "debug" resources, namely we could stream the logs of the docker containers `localdev-dnsmasq`, `k3d-localdev-serverlb`, `k3d-localdev-server-0` or `registry.lfr.dev`

**Comment by rotty3000** [comment]
See https://issues.liferay.com/browse/LXC-151
