### ISSUE TITLE
Start up extension environment contains configmaps from previous runs

### ISSUE THREAD

**Issue by gamerson** [liferay/liferay-localdev#24]
If you startup ext enviornment and deploy client extensions, DXP will write ConfigMaps into cluster.  However, next time you start EXT environment (in a different workspace), those ConfigMaps from previous deployment will show up.  This is because the CM data was persisted in DB and is being readded to cluster.

**Comment by gamerson** [comment]
Im' begining to wonder if we should have a different docker volume per workspace as the default? maybe we should let the dockerVolume be customizable by the TIltfile?

**Comment by rotty3000** [comment]
I've got a prototype of not persisting osgi configs that originated from configmaps that I believe would address this issue. I'll try to finalize it next week.

**Comment by rotty3000** [comment]
See https://issues.liferay.com/browse/LXC-153
