### ISSUE TITLE
Add a button to Tilt to generate a "Tiltfile" in user's workspace to help with Extending localdev

### ISSUE THREAD

**Issue by gamerson** [liferay/liferay-localdev#29]
It would be good if we could add some logic to main `Tiltfile` that would check to see if user has a `Tiltfile` in their workspace.  If they don't, we could add a button to the top panel of Tilt that would "generate a extension Tiltfile" in their workspace for them, that would look something like: https://github.com/gamerson/gartner-client-extensions-demo/blob/master/Tiltfile

**Comment by rotty3000** [comment]
See https://issues.liferay.com/browse/LXC-149
