### ISSUE TITLE
Add support for better cleaning up stale resources or pruning docker images that are stale

### ISSUE THREAD

**Issue by gamerson** [liferay/liferay-localdev#36]
We need to integrate better with `tilt doctor prune` and also docker prune or docker builder prune whenever disk pressure is getting hight.

**Comment by gamerson** [comment]
For reference: https://gist.github.com/rotty3000/fde2a265602c5b3fe6814db820c2bbdf

**Comment by rotty3000** [comment]
See https://issues.liferay.com/browse/LXC-145
