### ISSUE TITLE
Add better dev experience for debugging services or functions

### ISSUE THREAD

**Issue by gamerson** [liferay/liferay-localdev#37]
While debugging is possible right now for DXP or workloads, it requires quite a bit of knownledge and setup.  We should improve this dev experience.

[ ] debugging DXP source code
[ ] easy to setup debugging for java services / functions
[ ] easy to setup debugging for non-java services / functions in nodejs/gogin

**Comment by rotty3000** [comment]
See https://issues.liferay.com/browse/LXC-144
