### ISSUE TITLE
Introduce a more structured way to overlay resources to `dxp-server` image

### ISSUE THREAD

**Issue by gamerson** [liferay/liferay-localdev#67]
Right now we have support for overriding dxp-server image with ENVs, but it would be good if there was a general strategy for overlaying files in dxp image like we have in gradle-workspace with configs/<config>/osgi/ files.

**Comment by gamerson** [comment]
We added something quick and dirty here: https://github.com/liferay/liferay-localdev/pull/65

**Comment by rotty3000** [comment]
See https://issues.liferay.com/browse/LXC-136
