### ISSUE TITLE
Trying to stop localdev server when there are tilt errors fails to bring down environment

### ISSUE THREAD

**Issue by gamerson** [liferay/liferay-localdev#85]
If you have error sin your Tiltfile, and you call `liferay ext stop` the `tilt down` command that is executed inside container will fail and the container will not shut down.  I think perhaps we need a `-f` or `--force` option for `liferay extension stop` to ignore errors in Tilt down and just force a shutdown of container `docker container -f localdev-extension-runtime`

**Comment by rotty3000** [comment]
See https://issues.liferay.com/browse/LXC-132
